"""Declarative base and shared column conventions.

SQLAlchemy 2.x declarative style throughout. Mapped classes are persistence
mappings; they hold no business rules and expose no ``save()`` helper, because
commits belong to application use cases (ADR 0001).
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

__all__ = ["Base", "created_at_column", "internal_id_column", "metadata"]

# Deterministic constraint names. Without them PostgreSQL invents names that differ
# between environments, and Alembic cannot then generate a reliable downgrade or an
# ALTER that names a constraint.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Base(DeclarativeBase):
    """Base class for all mapped classes."""

    metadata = metadata

    def __repr__(self) -> str:
        """Show only the primary key.

        A generic attribute dump would eventually print a token column or personal
        data into a log or a traceback.
        """
        identity: Any = getattr(self, "id", None)
        return f"<{type(self).__name__} id={identity}>"


def internal_id_column() -> Mapped[uuid.UUID]:
    """Primary key column for an internal UUIDv7 identifier.

    No default is set here. Identifiers are generated by the application
    (``domain.identifiers.new_internal_id``) so an entity has identity before it is
    persisted, and so the value does not depend on a database extension.
    """
    return mapped_column(PgUUID(as_uuid=True), primary_key=True)


def created_at_column() -> Mapped[datetime]:
    """Creation timestamp, defaulted by the database in UTC.

    ``func.now()`` under PostgreSQL returns the transaction start time, so every row
    written in one transaction shares a timestamp. That is the desired behavior for
    an audit trail: it reflects the unit of work, not the moment of flush.
    """
    return mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
